# Global
## Set the domain to create nginx for argocd and other service ingress
domain: 
## Set local if you wish to start the local path provisioner for "local-path" in your cluster 
storage:
  local:
    enable: true
# Application specific
githubactionsrunner:
  enable: false
  token: ""
cats:
  storageClass: "local-path"
  #storageClass: "default-storageclass"
observability:
  storageClass: "local-path"
  #storageClass: "default-storageclass"
  pdkey:
  storageSize: 10Gi
  retention: 5d
trivy:
  enable: false
komodor:
  enable: false
  key:
  clustername:
logging:
  enable: true
metallb:
# This only passes through to the bootstrap resources a single address pool, 
# you can use a range if you you want to do something more complex
  addresspool: 10.0.0.80-10.0.0.85