# Global
## Set this to create nginx for argocd and other services
domain: cnskunkworks.io 
storage:
  local:
    enable: true
# Application specific
githubactionsrunner:
  enable: true
  token: ""
cats:
  storageClass: "local-path"
observability:
  storageClass: "local-path"
  pdkey:
  storageSize: 10Gi
  retention: 5d
trivy:
  enable: false
komodor:
  enable: false
  key:
  clustername:
logging:
  enable: true
