apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
 project: default
 source:
  repoURL: 'https://metallb.github.io/metallb'
  path: metallb
  targetRevision: 0.13.7
  helm:
    parameters:
        - name: prometheus.serviceMonitor.enabled
          value: "true"
 destination:
  server: 'https://kubernetes.default.svc'
  namespace: metallb-system
 syncPolicy:
  automated: {}