{{- if .Values.github-actions-runner.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runner
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
   link.argocd.argoproj.io/external-link: https://app.komodor.com/main/deep-dive/alex-jones.demo-cats.cats
spec:
 project: default
 source:
  repoURL: 'https://actions-runner-controller.github.io/actions-runner-controller'
  chart: actions-runner-controller/actions-runner-controller
  targetRevision: 0.21.0
  helm:
    parameters:
      - name: authSecret.create
        value: "true"
      - name: authSecret.github_token
        value: {{ .Values.github-actions-runner.token }}
 destination:
  server: 'https://kubernetes.default.svc'
  namespace: actions-runner-system
 syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
{{- end }}