apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
 project: runtime
source:
  repoURL: 'https://charts.longhorn.io'
  targetRevision: 1.3.2
  helm:
    releaseName: longhorn
  chart: longhorn
destination:
  server: 'https://kubernetes.default.svc'
  namespace: longhorn-system
syncPolicy:
  automated:
    selfHeal: true
  syncOptions:
    - Validate=false
    - CreateNamespace=true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m