apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
 destination:
  namespace: longhorn-system
  server: https://kubernetes.default.svc
 project: default
 source:
   chart: longhorn
   repoURL: 'https://charts.longhorn.io'
   targetRevision: 1.3.2
   helm:
    values: |
      fullnameOverride: longhorn
      defaultSettings:
        taintToleration: "home=true:NoSchedule"
        priorityClass: system-node-critical
      longhornManager:
        tolerations:
            - effect: NoSchedule
              key: home
              operator: Exists
      longhornDriver:
        tolerations:
            - effect: NoSchedule
              key: home
              operator: Exists
      longhornUI:
        tolerations:
            - effect: NoSchedule
              key: home
              operator: Exists
      persistence:
        reclaimPolicy: Retain
      ingress:
        enabled: true
        host: ***  
 syncPolicy:
  automated:
    prune: true
  syncOptions:
    - CreateNamespace=true