{{- if .Values.logging.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 1.8.11
    chart: loki-simple-scalable
    helm:
      parameters:
      - name: CommonConfig.replication_factor
        value: "1"
      - name: storage.type
        value: 'filesystem'
      - name: singleBinary.persistence.storageClassName
        value: 'local-path'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}