apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: open-feature-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/samples
    repoURL: https://github.com/open-feature/open-feature-operator/
    targetRevision: HEAD
  syncPolicy:
    automated: {}